CREATE DATABASE ProxyUnivRegDB;

USE ProxyUnivRegDB;

CREATE TABLE REGISTRY_UDDI
(
  REGISTRY_ID SMALLINT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  INQUIRY_URL VARCHAR(255) NOT NULL,
  PUBLISH_URL VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL,
  LAST_UPDATE TIMESTAMP NOT NULL,
  PRIMARY KEY (REGISTRY_ID)
);

CREATE TABLE UNSPSC
(
  COD_UNSPSC INT NOT NULL,
  DESCRIZIONE VARCHAR(255) NOT NULL,
  PRIMARY KEY (COD_UNSPSC)
);

CREATE TABLE NAICS
(
  COD_NAICS MEDIUMINT NOT NULL,
  DESCRIZIONE VARCHAR(255) NOT NULL,
  PRIMARY KEY (COD_NAICS)
);

CREATE TABLE ISO3166
(
  COD_ISO3166 VARCHAR(2) NOT NULL,
  NAZIONE VARCHAR(255) NOT NULL,
  PRIMARY KEY (COD_ISO3166)
);

CREATE TABLE CONTATORI_UNSPSC
(
  REGISTRY_ID SMALLINT NOT NULL,
  COD_UNSPSC INT NOT NULL,
  QUANTIT_WS INT,
  ACCESSI_WS INT,
  PRIMARY KEY (REGISTRY_ID,COD_UNSPSC),
  FOREIGN KEY (REGISTRY_ID)
    REFERENCES REGISTRY_UDDI (REGISTRY_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (COD_UNSPSC)
    REFERENCES UNSPSC (COD_UNSPSC)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CONTATORI_NAICS
(
  REGISTRY_ID SMALLINT NOT NULL,
  COD_NAICS MEDIUMINT NOT NULL,
  QUANTIT_WS INT,
  ACCESSI_WS INT,
  PRIMARY KEY (REGISTRY_ID,COD_NAICS),
  FOREIGN KEY (REGISTRY_ID)
    REFERENCES REGISTRY_UDDI (REGISTRY_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (COD_NAICS)
    REFERENCES NAICS (COD_NAICS)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CONTATORI_ISO3166
(
  REGISTRY_ID SMALLINT NOT NULL,
  COD_ISO3166 VARCHAR(2) NOT NULL,
  QUANTIT_WS INT,
  ACCESSI_WS INT,
  PRIMARY KEY (REGISTRY_ID,COD_ISO3166),
  FOREIGN KEY (REGISTRY_ID)
    REFERENCES REGISTRY_UDDI (REGISTRY_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (COD_ISO3166)
    REFERENCES ISO3166 (COD_ISO3166)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE AMMINISTRATORI
(
  AMM_ID SMALLINT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL,
  PRIMARY KEY (AMM_ID)
);

CREATE TABLE AGGIUNTE_REGISTRY
(
  AMM_ID SMALLINT NOT NULL AUTO_INCREMENT,
  REGISTRY_ID SMALLINT NOT NULL,
  DATA_AGGIUNTA DATE,
  PRIMARY KEY (AMM_ID, REGISTRY_ID),
  FOREIGN KEY (AMM_ID)
    REFERENCES AMMINISTRATORI (AMM_ID),
  FOREIGN KEY (REGISTRY_ID)
    REFERENCES REGISTRY_UDDI (REGISTRY_ID)
    ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO AMMINISTRATORI (USERNAME,PASSWORD)
VALUES ('amini1719','passs1720');

INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (10000000,'Live Plant and Animal Material and Accessories and Supplies');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (20000000,'Mining and Well Drilling Machinery and Accessories');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (30000000,'Structures and Building and Construction and Manufacturing Components and Supplies');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (40000000,'Distribution and Conditioning Systems and Equipment and Components');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (50000000,'Food Beverage and Tobacco Products');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (60000000,'Musical Instruments and Games and Toys and Arts and Crafts and Educational Equipment and Materials and Accessories and Supplies');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (70000000,'Farming and Fishing and Forestry and Wildlife Contracting Services');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (80000000,'Management and Business Professionals and Administrative Services');
INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)
VALUES (90000000,'Travel and Food and Lodging and Entertainment Services');

INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (11,'Agriculture, Forestry, Fishing and Hunting');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (21,'Mining');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (22,'Utilities');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (23,'Construction');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (31,'Manufacturing-31');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (32,'Manufacturing-32');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (33,'Manufacturing-33');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (42,'Wholesale Trade');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (44,'Retail Trade-44');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (45,'Retail Trade-45');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (48,'Transportation and Warehousing-48');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (49,'Transportation and Warehousing-49');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (51,'Information');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (52,'Finance and Insurance');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (53,'Real Estate and Rental and Leasing');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (54,'Professional, Scientific, and Technical Services');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (55,'Management of Companies and Enterprises');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (56,'Administrative and Support and Waste Management and Remediation Services');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (61,'Educational Services');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (62,'Health Care and Social Assistance');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (71,'Arts, Entertainment, and Recreation');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (72,'Accommodation and Food Services');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (81,'Other Services (except Public Administration)');
INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)
VALUES (92,'Public Administration');

INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AF','AFGHANISTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AL','ALBANIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('DZ','ALGERIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AS','AMERICAN SAMOA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AD','ANDORRA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AO','ANGOLA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AI','ANGUILLA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AQ','ANTARCTICA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AG','ANTIGUA AND BARBUDA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AR','ARGENTINA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AM','ARMENIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AW','ARUBA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AU','AUSTRALIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AT','AUSTRIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AZ','AZERBAIJAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BS','BAHAMAS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BH','BAHRAIN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BD','BANGLADESH');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BB','BARBADOS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BY','BELARUS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BE','BELGIUM');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BZ','BELIZE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BJ','BENIN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BM','BERMUDA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BT','BHUTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BO','BOLIVIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BA','BOSNIA AND HERZEGOVINA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BW','BOTSWANA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BV','BOUVET ISLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BR','BRAZIL');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IO','BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BN','BRUNEI DARUSSALAM');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BG','BULGARIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BF','BURKINA FASO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('BI','BURUNDI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KH','CAMBODIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CM','CAMEROON');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CA','CANADA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CV','CAPE VERDE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KY','CAYMAN ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CF','CENTRAL AFRICAN REPUBLIC');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TD','CHAD');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CL','CHILE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CN','CHINA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CX','CHRISTMAS ISLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CC','COCOS (KEELING) ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CO','COLOMBIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KM','COMOROS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CG','CONGO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CK','COOK ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CR','COSTA RICA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CI','COTE D''IVOIRE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('HR','CROATIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CU','CUBA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CY','CYPRUS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CZ','CZECH REPUBLIC');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('DK','DENMARK');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('DJ','DJIBOUTI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('DM','DOMINICA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('DO','DOMINICAN REPUBLIC');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TP','EAST TIMOR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('EC','ECUADOR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('EG','EGYPT');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SV','EL SALVADOR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GQ','EQUATORIAL GUINEA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ER','ERITREA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('EE','ESTONIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ET','ETHIOPIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('FK','FALKLAND ISLANDS (MALVINAS)');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('FO','FAROE ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('FJ','FIJI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('FI','FINLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('FR','FRANCE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GF','FRENCH GUIANA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PF','FRENCH POLYNESIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TF','FRENCH SOUTHERN TERRITORIES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GA','GABON');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GM','GAMBIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GE','GEORGIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('DE','GERMANY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GH','GHANA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GI','GIBRALTAR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GR','GREECE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GL','GREENLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GD','GRENADA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GP','GUADELOUPE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GU','GUAM');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GT','GUATEMALA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GN','GUINEA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GW','GUINEA-BISSAU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GY','GUYANA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('HT','HAITI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('HM','HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VA','HOLY SEE (VATICAN CITY STATE)');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('HN','HONDURAS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('HK','HONG KONG');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('HU','HUNGARY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IS','ICELAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IN','INDIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ID','INDONESIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IQ','IRAQ');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IE','IRELAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IL','ISRAEL');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('IT','ITALY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('JM','JAMAICA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('JP','JAPAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('JO','JORDAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KZ','KAZAKSTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KE','KENYA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KI','KIRIBATI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KR','KOREA, REPUBLIC OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KW','KUWAIT');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KG','KYRGYZSTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LV','LATVIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LB','LEBANON');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LS','LESOTHO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LR','LIBERIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LY','LIBYAN ARAB JAMAHIRIYA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LI','LIECHTENSTEIN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LT','LITHUANIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LU','LUXEMBOURG');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MO','MACAU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MG','MADAGASCAR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MW','MALAWI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MY','MALAYSIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MV','MALDIVES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ML','MALI');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MT','MALTA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MH','MARSHALL ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MQ','MARTINIQUE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MR','MAURITANIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MU','MAURITIUS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('YT','MAYOTTE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MX','MEXICO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('FM','MICRONESIA, FEDERATED STATES OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MD','MOLDOVA, REPUBLIC OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MC','MONACO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MN','MONGOLIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MS','MONTSERRAT');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MA','MOROCCO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MZ','MOZAMBIQUE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MM','MYANMAR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NA','NAMIBIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NR','NAURU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NP','NEPAL');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NL','NETHERLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AN','NETHERLANDS ANTILLES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NC','NEW CALEDONIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NZ','NEW ZEALAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NI','NICARAGUA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NE','NIGER');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NG','NIGERIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NU','NIUE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NF','NORFOLK ISLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('MP','NORTHERN MARIANA ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('NO','NORWAY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('OM','OMAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PK','PAKISTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PW','PALAU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PS','PALESTINIAN TERRITORY, OCCUPIED');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PA','PANAMA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PG','PAPUA NEW GUINEA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PY','PARAGUAY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PE','PERU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PH','PHILIPPINES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PN','PITCAIRN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PL','POLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PT','PORTUGAL');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PR','PUERTO RICO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('QA','QATAR');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('RE','REUNION');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('RO','ROMANIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('RU','RUSSIAN FEDERATION');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('RW','RWANDA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SH','SAINT HELENA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('KN','SAINT KITTS AND NEVIS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LC','SAINT LUCIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('PM','SAINT PIERRE AND MIQUELON');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VC','SAINT VINCENT AND THE GRENADINES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('WS','SAMOA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SM','SAN MARINO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ST','SAO TOME AND PRINCIPE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SA','SAUDI ARABIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SN','SENEGAL');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SC','SEYCHELLES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SL','SIERRA LEONE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SG','SINGAPORE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SK','SLOVAKIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SI','SLOVENIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SB','SOLOMON ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SO','SOMALIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ZA','SOUTH AFRICA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ES','SPAIN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('LK','SRI LANKA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SD','SUDAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SR','SURINAME');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SJ','SVALBARD AND JAN MAYEN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SZ','SWAZILAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SE','SWEDEN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('CH','SWITZERLAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('SY','SYRIAN ARAB REPUBLIC');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TW','TAIWAN, PROVINCE OF CHINA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TJ','TAJIKISTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TH','THAILAND');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TG','TOGO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TK','TOKELAU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TO','TONGA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TT','TRINIDAD AND TOBAGO');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TN','TUNISIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TR','TURKEY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TM','TURKMENISTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TC','TURKS AND CAICOS ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('TV','TUVALU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('UG','UGANDA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('UA','UKRAINE');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('AE','UNITED ARAB EMIRATES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('GB','UNITED KINGDOM');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('US','UNITED STATES');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('UM','UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('UY','URUGUAY');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('UZ','UZBEKISTAN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VU','VANUATU');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VE','VENEZUELA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VN','VIET NAM');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VG','VIRGIN ISLANDS, BRITISH');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('VI','VIRGIN ISLANDS, U.S.');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('WF','WALLIS AND FUTUNA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('EH','WESTERN SAHARA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('YE','YEMEN');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('YU','YUGOSLAVIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ZM','ZAMBIA');
INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)
VALUES ('ZW','ZIMBABWE');
