#include <stdio.h>
#define N 265
#define U 255
#define P 16
#define NomeFile "create_DB.sql"

void ConcatenaStringhe(char [], char [], char []);

int main()
{
    char username[U+1];
    char password[P+1];
    char concatenamento[N+1];
    char sC[(2*N)+1];
    FILE *fp;
    
    printf("***********************************************************\n");
    printf("     Script inizializzazione database ProxyUnivRegDB\n");
    printf("***********************************************************\n\n");
    
    do
    {
      printf("Username [primo] amministratore (max 255 caratteri): ");
      gets(username); 
      printf("Numero caratteri username = %d\n",strlen(username));
    }
    while ( strlen(username) > 255 );
    
    do
    {
      printf("Password [primo] amministratore (max 16 caratteri): ");
      gets(password);
      printf("Numero caratteri password = %d\n",strlen(password));
    }
    while ( strlen(password) > 16);
    
    fp = fopen(NomeFile,"w"); 
    
    fprintf(fp,"%s\n","CREATE DATABASE ProxyUnivRegDB;"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","USE ProxyUnivRegDB;"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE REGISTRY_UDDI"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  REGISTRY_ID SMALLINT NOT NULL AUTO_INCREMENT,"); 
    fprintf(fp,"%s\n","  NOME VARCHAR(30) NOT NULL,"); 
    fprintf(fp,"%s\n","  INQUIRY_URL VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  PUBLISH_URL VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  USERNAME VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  PASSWORD VARCHAR(16) NOT NULL,"); 
    fprintf(fp,"%s\n","  LAST_UPDATE TIMESTAMP NOT NULL,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (REGISTRY_ID)"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE UNSPSC"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  COD_UNSPSC INT NOT NULL,"); 
    fprintf(fp,"%s\n","  DESCRIZIONE VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (COD_UNSPSC)"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE NAICS"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  COD_NAICS MEDIUMINT NOT NULL,"); 
    fprintf(fp,"%s\n","  DESCRIZIONE VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (COD_NAICS)"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE ISO3166"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  COD_ISO3166 VARCHAR(2) NOT NULL,"); 
    fprintf(fp,"%s\n","  NAZIONE VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (COD_ISO3166)"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE CONTATORI_UNSPSC"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  REGISTRY_ID SMALLINT NOT NULL,"); 
    fprintf(fp,"%s\n","  COD_UNSPSC INT NOT NULL,"); 
    fprintf(fp,"%s\n","  QUANTIT_WS INT,"); 
    fprintf(fp,"%s\n","  ACCESSI_WS INT,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (REGISTRY_ID,COD_UNSPSC),"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    REFERENCES REGISTRY_UDDI (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE,"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (COD_UNSPSC)"); 
    fprintf(fp,"%s\n","    REFERENCES UNSPSC (COD_UNSPSC)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE CONTATORI_NAICS"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  REGISTRY_ID SMALLINT NOT NULL,"); 
    fprintf(fp,"%s\n","  COD_NAICS MEDIUMINT NOT NULL,"); 
    fprintf(fp,"%s\n","  QUANTIT_WS INT,"); 
    fprintf(fp,"%s\n","  ACCESSI_WS INT,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (REGISTRY_ID,COD_NAICS),"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    REFERENCES REGISTRY_UDDI (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE,"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (COD_NAICS)"); 
    fprintf(fp,"%s\n","    REFERENCES NAICS (COD_NAICS)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE CONTATORI_ISO3166"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  REGISTRY_ID SMALLINT NOT NULL,"); 
    fprintf(fp,"%s\n","  COD_ISO3166 VARCHAR(2) NOT NULL,"); 
    fprintf(fp,"%s\n","  QUANTIT_WS INT,"); 
    fprintf(fp,"%s\n","  ACCESSI_WS INT,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (REGISTRY_ID,COD_ISO3166),"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    REFERENCES REGISTRY_UDDI (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE,"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (COD_ISO3166)"); 
    fprintf(fp,"%s\n","    REFERENCES ISO3166 (COD_ISO3166)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE AMMINISTRATORI"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  AMM_ID SMALLINT NOT NULL AUTO_INCREMENT,"); 
    fprintf(fp,"%s\n","  USERNAME VARCHAR(255) NOT NULL,"); 
    fprintf(fp,"%s\n","  PASSWORD VARCHAR(16) NOT NULL,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (AMM_ID)"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","CREATE TABLE AGGIUNTE_REGISTRY"); 
    fprintf(fp,"%s\n","("); 
    fprintf(fp,"%s\n","  AMM_ID SMALLINT NOT NULL AUTO_INCREMENT,"); 
    fprintf(fp,"%s\n","  REGISTRY_ID SMALLINT NOT NULL,"); 
    fprintf(fp,"%s\n","  DATA_AGGIUNTA DATE,"); 
    fprintf(fp,"%s\n","  PRIMARY KEY (AMM_ID, REGISTRY_ID),"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (AMM_ID)"); 
    fprintf(fp,"%s\n","    REFERENCES AMMINISTRATORI (AMM_ID),"); 
    fprintf(fp,"%s\n","  FOREIGN KEY (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    REFERENCES REGISTRY_UDDI (REGISTRY_ID)"); 
    fprintf(fp,"%s\n","    ON UPDATE CASCADE ON DELETE CASCADE"); 
    fprintf(fp,"%s\n",");"); 
    fprintf(fp,"%s\n",""); 
    
    printf("\nCreata la struttura delle tabelle del database.\n");
    
    fprintf(fp,"%s\n","INSERT INTO AMMINISTRATORI (USERNAME,PASSWORD)"); 
     ConcatenaStringhe(sC,"VALUES ('",username);
     ConcatenaStringhe(sC,sC,"','");
     ConcatenaStringhe(sC,sC,password);
     ConcatenaStringhe(sC,sC,"');");
    fprintf(fp,"%s\n",&sC);
    
    printf("Salvati i dati del primo amministratore.\n");
    
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (10000000,'Live Plant and Animal Material and Accessories and Supplies');"); 
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (20000000,'Mining and Well Drilling Machinery and Accessories');");
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (30000000,'Structures and Building and Construction and Manufacturing Components and Supplies');"); 
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (40000000,'Distribution and Conditioning Systems and Equipment and Components');");      
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (50000000,'Food Beverage and Tobacco Products');"); 
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (60000000,'Musical Instruments and Games and Toys and Arts and Crafts and Educational Equipment and Materials and Accessories and Supplies');");
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (70000000,'Farming and Fishing and Forestry and Wildlife Contracting Services');"); 
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (80000000,'Management and Business Professionals and Administrative Services');");      
    fprintf(fp,"%s\n","INSERT INTO UNSPSC (COD_UNSPSC,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (90000000,'Travel and Food and Lodging and Entertainment Services');");
    fprintf(fp,"%s\n",""); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (11,'Agriculture, Forestry, Fishing and Hunting');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (21,'Mining');");
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (22,'Utilities');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (23,'Construction');");      
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (31,'Manufacturing-31');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (32,'Manufacturing-32');");
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (33,'Manufacturing-33');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (42,'Wholesale Trade');");      
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (44,'Retail Trade-44');");  
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (45,'Retail Trade-45');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (48,'Transportation and Warehousing-48');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (49,'Transportation and Warehousing-49');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (51,'Information');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (52,'Finance and Insurance');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (53,'Real Estate and Rental and Leasing');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (54,'Professional, Scientific, and Technical Services');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (55,'Management of Companies and Enterprises');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (56,'Administrative and Support and Waste Management and Remediation Services');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (61,'Educational Services');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (62,'Health Care and Social Assistance');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (71,'Arts, Entertainment, and Recreation');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (72,'Accommodation and Food Services');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (81,'Other Services (except Public Administration)');"); 
    fprintf(fp,"%s\n","INSERT INTO NAICS (COD_NAICS,DESCRIZIONE)"); 
    fprintf(fp,"%s\n","VALUES (92,'Public Administration');"); 
    fprintf(fp,"%s\n","");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AF','AFGHANISTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AL','ALBANIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('DZ','ALGERIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AS','AMERICAN SAMOA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AD','ANDORRA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AO','ANGOLA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AI','ANGUILLA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AQ','ANTARCTICA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AG','ANTIGUA AND BARBUDA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AR','ARGENTINA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AM','ARMENIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AW','ARUBA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AU','AUSTRALIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AT','AUSTRIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AZ','AZERBAIJAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BS','BAHAMAS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BH','BAHRAIN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BD','BANGLADESH');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BB','BARBADOS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BY','BELARUS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BE','BELGIUM');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BZ','BELIZE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BJ','BENIN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BM','BERMUDA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BT','BHUTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BO','BOLIVIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BA','BOSNIA AND HERZEGOVINA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BW','BOTSWANA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BV','BOUVET ISLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BR','BRAZIL');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IO','BRITISH INDIAN OCEAN TERRITORY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BN','BRUNEI DARUSSALAM');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BG','BULGARIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BF','BURKINA FASO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('BI','BURUNDI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KH','CAMBODIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CM','CAMEROON');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CA','CANADA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CV','CAPE VERDE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KY','CAYMAN ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CF','CENTRAL AFRICAN REPUBLIC');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TD','CHAD');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CL','CHILE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CN','CHINA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CX','CHRISTMAS ISLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CC','COCOS (KEELING) ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CO','COLOMBIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KM','COMOROS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CG','CONGO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CK','COOK ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CR','COSTA RICA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CI','COTE D''IVOIRE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('HR','CROATIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CU','CUBA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CY','CYPRUS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CZ','CZECH REPUBLIC');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('DK','DENMARK');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('DJ','DJIBOUTI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('DM','DOMINICA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('DO','DOMINICAN REPUBLIC');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TP','EAST TIMOR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('EC','ECUADOR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('EG','EGYPT');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SV','EL SALVADOR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GQ','EQUATORIAL GUINEA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ER','ERITREA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('EE','ESTONIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ET','ETHIOPIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('FK','FALKLAND ISLANDS (MALVINAS)');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('FO','FAROE ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('FJ','FIJI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('FI','FINLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('FR','FRANCE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GF','FRENCH GUIANA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PF','FRENCH POLYNESIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TF','FRENCH SOUTHERN TERRITORIES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GA','GABON');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GM','GAMBIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GE','GEORGIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('DE','GERMANY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GH','GHANA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GI','GIBRALTAR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GR','GREECE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GL','GREENLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GD','GRENADA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GP','GUADELOUPE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GU','GUAM');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GT','GUATEMALA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GN','GUINEA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GW','GUINEA-BISSAU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GY','GUYANA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('HT','HAITI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('HM','HEARD ISLAND AND MCDONALD ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VA','HOLY SEE (VATICAN CITY STATE)');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('HN','HONDURAS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('HK','HONG KONG');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('HU','HUNGARY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IS','ICELAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IN','INDIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ID','INDONESIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IQ','IRAQ');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IE','IRELAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IL','ISRAEL');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('IT','ITALY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('JM','JAMAICA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('JP','JAPAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('JO','JORDAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KZ','KAZAKSTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KE','KENYA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KI','KIRIBATI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KR','KOREA, REPUBLIC OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KW','KUWAIT');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KG','KYRGYZSTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LV','LATVIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LB','LEBANON');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LS','LESOTHO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LR','LIBERIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LY','LIBYAN ARAB JAMAHIRIYA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LI','LIECHTENSTEIN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LT','LITHUANIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LU','LUXEMBOURG');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MO','MACAU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MG','MADAGASCAR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MW','MALAWI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MY','MALAYSIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MV','MALDIVES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ML','MALI');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MT','MALTA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MH','MARSHALL ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MQ','MARTINIQUE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MR','MAURITANIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MU','MAURITIUS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('YT','MAYOTTE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MX','MEXICO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('FM','MICRONESIA, FEDERATED STATES OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MD','MOLDOVA, REPUBLIC OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MC','MONACO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MN','MONGOLIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MS','MONTSERRAT');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MA','MOROCCO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MZ','MOZAMBIQUE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MM','MYANMAR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NA','NAMIBIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NR','NAURU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NP','NEPAL');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NL','NETHERLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AN','NETHERLANDS ANTILLES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NC','NEW CALEDONIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NZ','NEW ZEALAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NI','NICARAGUA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NE','NIGER');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NG','NIGERIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NU','NIUE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NF','NORFOLK ISLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('MP','NORTHERN MARIANA ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('NO','NORWAY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('OM','OMAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PK','PAKISTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PW','PALAU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PS','PALESTINIAN TERRITORY, OCCUPIED');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PA','PANAMA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PG','PAPUA NEW GUINEA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PY','PARAGUAY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PE','PERU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PH','PHILIPPINES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PN','PITCAIRN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PL','POLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PT','PORTUGAL');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PR','PUERTO RICO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('QA','QATAR');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('RE','REUNION');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('RO','ROMANIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('RU','RUSSIAN FEDERATION');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('RW','RWANDA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SH','SAINT HELENA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('KN','SAINT KITTS AND NEVIS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LC','SAINT LUCIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('PM','SAINT PIERRE AND MIQUELON');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VC','SAINT VINCENT AND THE GRENADINES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('WS','SAMOA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SM','SAN MARINO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ST','SAO TOME AND PRINCIPE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SA','SAUDI ARABIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SN','SENEGAL');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SC','SEYCHELLES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SL','SIERRA LEONE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SG','SINGAPORE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SK','SLOVAKIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SI','SLOVENIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SB','SOLOMON ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SO','SOMALIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ZA','SOUTH AFRICA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ES','SPAIN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('LK','SRI LANKA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SD','SUDAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SR','SURINAME');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SJ','SVALBARD AND JAN MAYEN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SZ','SWAZILAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SE','SWEDEN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('CH','SWITZERLAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('SY','SYRIAN ARAB REPUBLIC');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TW','TAIWAN, PROVINCE OF CHINA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TJ','TAJIKISTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TH','THAILAND');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TG','TOGO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TK','TOKELAU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TO','TONGA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TT','TRINIDAD AND TOBAGO');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TN','TUNISIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TR','TURKEY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TM','TURKMENISTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TC','TURKS AND CAICOS ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('TV','TUVALU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('UG','UGANDA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('UA','UKRAINE');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('AE','UNITED ARAB EMIRATES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('GB','UNITED KINGDOM');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('US','UNITED STATES');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('UM','UNITED STATES MINOR OUTLYING ISLANDS');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('UY','URUGUAY');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('UZ','UZBEKISTAN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VU','VANUATU');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VE','VENEZUELA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VN','VIET NAM');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VG','VIRGIN ISLANDS, BRITISH');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('VI','VIRGIN ISLANDS, U.S.');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('WF','WALLIS AND FUTUNA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('EH','WESTERN SAHARA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('YE','YEMEN');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('YU','YUGOSLAVIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ZM','ZAMBIA');");
    fprintf(fp,"%s\n","INSERT INTO ISO3166 (COD_ISO3166,NAZIONE)"); 
    fprintf(fp,"%s\n","VALUES ('ZW','ZIMBABWE');");
    
    fclose(fp);
   
    system("mysql -uroot -p123456 <create_DB.sql");
    
    printf("Riempimento delle tabelle standard UNSPSC, NAICS, ISO3166.\n");
    printf("\nIniziazializzaione del database completata con successo!\n");
    
    printf("\n\n");
    system("Pause");
}

void ConcatenaStringhe(char strConcat[], char str1[], char str2[])
{
     int i,j;
     
     for (i=0; str1[i]!='\0'; i++) strConcat[i] = str1[i];
     for (j=0; str2[j]!='\0'; i++, j++) strConcat[i] = str2[j];
     
     strConcat[i]='\0';
}
